### PR TITLE
Fix credentials-verification workflow

### PR DESCRIPTION
**Pull request by jdisanti**
_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by jdisanti** [comment]
Tested the fix by manually kicking it off against this branch: https://github.com/smithy-lang/smithy-rs/actions/runs/7938459322

**Review by rcoh — APPROVED** [review]
Weird this definitely used to work

**Comment by jdisanti** [comment]
The Rust version isn't pinned down in this workflow, so perhaps something changed there.

**Comment by ysaito1001** [comment]
> The Rust version isn't pinned down in this workflow, so perhaps something changed there.

Thanks for fixing!

**Pull request merged**
