### PR TITLE
Fix maps/lists with sensitive members not redacted

### PR DESCRIPTION
**Pull request by landonxjames**
## Motivation and Context

Lists and maps with sensitive members were not being properly redacted. Closes https://github.com/smithy-lang/smithy-rs/issues/3757

## Description

Updated `Shape.shouldRedact` method to properly check for list and map shapes with sensitive members. Also updated the test definition so it would actually run since previously the test code was generated in a nested function inside a no-op function and never run.

## Testing

Added test cases for lists with sensitive members, maps with sensitive keys, and maps with sensitive values. 

## Checklist

- [x] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by aajtodd — COMMENTED** [review]
This has [a lot of changes](https://d2luzm2xt3nokh.cloudfront.net/codegen-diff/0b059fb5e501d331dc688ee23fdc68581cf0bb0b/5a651004c2aecc83c1dd65f43bc60a12348b70b7/aws-sdk/index.html) that actually seem to relax debug/display implementations. Have you verified this is the desired/correct behavior change? Were we over redacting before?

**Comment by landonxjames** [comment]
> This has [a lot of changes](https://d2luzm2xt3nokh.cloudfront.net/codegen-diff/0b059fb5e501d331dc688ee23fdc68581cf0bb0b/5a651004c2aecc83c1dd65f43bc60a12348b70b7/aws-sdk/index.html) that actually seem to relax debug/display implementations. Have you verified this is the desired/correct behavior change? Were we over redacting before?

Good catch! That was a bug (same one causing the CI failures) and should be fixed in https://github.com/smithy-lang/smithy-rs/pull/3765/commits/4b398c752e573dd4fa55abb9ad6fa802b1d1263a

**Review by aajtodd — APPROVED** [review]

**Review by ysaito1001 — APPROVED** [review]

**Comment by ysaito1001** [comment]
Probably this warrants a  `CHANGELOG` entry with a bug-fix being true.

**Comment by david-perez** [comment]
This needs to be ported over to `ServerBuilderGenerator` too.

It also looks like we never added `Debug` implementation to `ServerBuilderGeneratorWithoutPublicConstrainedTypes`.

**Pull request merged**
