### PR TITLE
Fix private-in-public error in rustc before 1.74.0

### PR DESCRIPTION
**Pull request by nerdile**
## Motivation and Context
Rustc 1.74.0 removed the private-in-public check, which raises a compile-time error if a member of a struct has a type which is less visible than the parent struct.  Fixing this private-in-public issue enables aws-smithy-runtime to build in projects using rustc older than 1.74.0.

## Description
Make UploadThroughputCheckFuture pub(crate) because it is needed in MaybeUploadThroughputCheckFuture which is pub(crate).

## Testing
Verified that crate now compiles using rustc 1.72.1.

## Checklist

- [x] I have updated `CHANGELOG.next.toml` if I made changes to the smithy-rs codegen or runtime crates
- [x] I have updated `CHANGELOG.next.toml` if I made changes to the AWS SDK, generated SDK code, or SDK runtime crates

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Review by rcoh — APPROVED** [review]

**Review by ysaito1001 — APPROVED** [review]
LGTM, we probably just need to bump a patch version of `aws-smithy-runtime` in its Cargo.toml

**Comment by nerdile** [comment]
@rcoh : 
* PR bot and canary cannot be invoked from a forked repository. Ask a maintainer to manually invoke them using your PR.
* check-sdk-codegen-unit-tests failing to find recently published tokio-macros crate
Anything I can do to resolve these?

**Comment by nerdile** [comment]
> LGTM, we probably just need to bump a patch version of `aws-smithy-runtime` in its Cargo.toml

Thanks @ysaito1001 , is this something I should address or will the team take care of it?

**Comment by ysaito1001** [comment]
We'll handle the rest and get it merged because the rest is a small chore. Thanks for the PR!

**Pull request merged**
