### PR TITLE
Delete nonprintable characters from aws-smithy-checksums test

### PR DESCRIPTION
**Pull request by dtolnay**
## Motivation and Context

The nonprintable characters in this source file make tools misidentify it as a binary file, rather than source code.

## Description

**Before:**

```console
$ file rust-runtime/aws-smithy-checksums/src/http.rs
rust-runtime/aws-smithy-checksums/src/http.rs: data
```

**After:**

```console
$ file rust-runtime/aws-smithy-checksums/src/http.rs
rust-runtime/aws-smithy-checksums/src/http.rs: ASCII text
```

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by dtolnay** [comment]
Additionally, I recommend finding a way to re-review all previous changes to this file, as it's likely they went unreviewed in the first place.

- https://github.com/smithy-lang/smithy-rs/pull/1561/files#diff-6982e78269354e1051152534be8202ee5b606d495c5d7555dff307962ec27dfa
- https://github.com/smithy-lang/smithy-rs/pull/1938/files#diff-6982e78269354e1051152534be8202ee5b606d495c5d7555dff307962ec27dfa
- https://github.com/smithy-lang/smithy-rs/pull/3059/files#diff-6982e78269354e1051152534be8202ee5b606d495c5d7555dff307962ec27dfa

**Comment by dtolnay** [comment]
```console
# Auditing runtime crate version numbers...
2024-08-01T19:23:27.698077Z  INFO runtime_versioner::command::audit: 'aws-config' changed and was version bumped from 1.5.4 to 1.5.5
2024-08-01T19:23:27.730127Z  INFO runtime_versioner::command::audit: 'aws-smithy-cbor' is a new crate (or wasn't independently versioned before) and will publish at 0.60.7
2024-08-01T19:23:27.755161Z  INFO runtime_versioner::command::audit: 'aws-smithy-http-server' changed and was version bumped from 0.63.1 to 0.63.2
2024-08-01T19:23:27.769870Z  INFO runtime_versioner::command::audit: 'aws-smithy-protocol-test' changed and was version bumped from 0.60.8 to 0.62.0
aws-smithy-checksums changed since release-2024-07-16 and requires a version bump
Error: there are audit failures in the runtime crates
```

**Comment by dtolnay** [comment]
```console
PR bot and canary cannot be invoked from a forked repository. Ask a maintainer to manually invoke them using your PR.
Error: Process completed with exit code 1.
```

**Comment by ysaito1001** [comment]
> ```
> PR bot and canary cannot be invoked from a forked repository. Ask a maintainer to manually invoke them using your PR.
> Error: Process completed with exit code 1.
> ```

Currently running it [here](https://github.com/smithy-lang/smithy-rs/actions/runs/10207575049). 

This step is always marked as failure in PRs created from forked repos (we don't have a good way to communicate that in GitHub jobs result icons), but it is not a required step for PRs to be merged.

**Comment by dtolnay** [comment]
Rebased to resolve conflict with https://github.com/smithy-lang/smithy-rs/pull/3781 in aws/rust-runtime/Cargo.lock.

**Review by Velfi — APPROVED** [review]

**Pull request merged**
