### PR TITLE
fix: update test operation generator to find any operation in the service closure

### PR DESCRIPTION
**Pull request by mcmasn-amzn**
## Motivation and Context
When using operations nested under resources, the current search will raise "NoSuchElementException". This fixes the search to include all operations within the service closure

## Description
The error is visible in client generates like this:
```
Projection rust-client failed: java.util.NoSuchElementException: Collection contains no element matching the predicate.
java.util.NoSuchElementException: Collection contains no element matching the predicate.
        at software.amazon.smithy.rustsdk.endpoints.OperationInputTestGeneratorKt.operationId(OperationInputTestGenerator.kt:242)
        at software.amazon.smithy.rustsdk.endpoints.OperationInputTestGenerator$operationInvocation$1.invoke(OperationInputTestGenerator.kt:183)
        at software.amazon.smithy.rustsdk.endpoints.OperationInputTestGenerator$operationInvocation$1.invoke(OperationInputTestGenerator.kt:180)
```

## Testing
`gradle :aws:sdk-codegen:check`
## Checklist

- [ ] For changes to the smithy-rs codegen or runtime crates, I have created a changelog entry Markdown file in the `.changelog` directory, specifying "client," "server," or both in the `applies_to` key.
- [ ] For changes to the AWS SDK, generated SDK code, or SDK runtime crates, I have created a changelog entry Markdown file in the `.changelog` directory, specifying "aws-sdk-rust" in the `applies_to` key.

----

_By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice._

### CODE REVIEW

**Comment by landonxjames** [comment]
Canary run: https://github.com/smithy-lang/smithy-rs/actions/runs/12243815464

**Review by landonxjames — APPROVED** [review]
Having to use a Smithy index like this instead of just iterating through all the operations is a bit of a smithy footgun and I think there are probably several other places in the codebase that do this. Thanks for catching it and providing the test!

**Comment by mcmasn-amzn** [comment]
Thanks @landonxjames. Yes, I wrote the original code here in 2023 and didn't realize `serviceShape.allOperations` doesn't recurse through attached resources. It's a surprising behavior, but also, one that's probably tricky to fix without breaking existing callers.

**Comment by landonxjames** [comment]
Canary passed and the semver test failure is currently expected, merging

**Pull request merged**
